version: '3.9'

services:
  endpoints:
    image: python:3.12-slim
    volumes:
      - .:/app
    command: tail -f /dev/null
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"